// TOCFL Chinese Learning — Traditional Chinese data

const VOCABULARY = [
  // Chapter 1 - Greetings
  { id: "v001", word: "你好", pinyin: "nǐ hǎo", meaning: "hello", example: "你好！很高興認識你。", exampleEn: "Hello! Nice to meet you.", pos: "interjection", chapter: 1, tags: ["greetings"] },
  { id: "v002", word: "您好", pinyin: "nín hǎo", meaning: "hello (polite)", example: "您好，請問您貴姓？", exampleEn: "Hello, may I ask your surname?", pos: "interjection", chapter: 1, tags: ["greetings"] },
  { id: "v003", word: "謝謝", pinyin: "xiè xiè", meaning: "thank you", example: "謝謝你的幫忙。", exampleEn: "Thank you for your help.", pos: "interjection", chapter: 1, tags: ["greetings"] },
  { id: "v004", word: "不客氣", pinyin: "bù kè qì", meaning: "you're welcome", example: "不客氣，這是我應該做的。", exampleEn: "You're welcome, it's what I should do.", pos: "phrase", chapter: 1, tags: ["greetings"] },
  { id: "v005", word: "對不起", pinyin: "duì bu qǐ", meaning: "sorry; excuse me", example: "對不起，我遲到了。", exampleEn: "Sorry, I'm late.", pos: "phrase", chapter: 1, tags: ["greetings"] },
  { id: "v006", word: "沒關係", pinyin: "méi guān xi", meaning: "never mind; it's okay", example: "沒關係，下次注意就好了。", exampleEn: "Never mind, just be careful next time.", pos: "phrase", chapter: 1, tags: ["greetings"] },
  { id: "v007", word: "請問", pinyin: "qǐng wèn", meaning: "excuse me (to ask); may I ask", example: "請問，廁所在哪裡？", exampleEn: "Excuse me, where is the restroom?", pos: "phrase", chapter: 1, tags: ["greetings"] },
  { id: "v008", word: "再見", pinyin: "zài jiàn", meaning: "goodbye", example: "再見！明天見。", exampleEn: "Goodbye! See you tomorrow.", pos: "interjection", chapter: 1, tags: ["greetings"] },
  { id: "v009", word: "早安", pinyin: "zǎo ān", meaning: "good morning", example: "早安！你吃早餐了嗎？", exampleEn: "Good morning! Have you had breakfast?", pos: "interjection", chapter: 1, tags: ["greetings"] },
  { id: "v010", word: "晚安", pinyin: "wǎn ān", meaning: "good night", example: "晚安，好好睡覺。", exampleEn: "Good night, sleep well.", pos: "interjection", chapter: 1, tags: ["greetings"] },
  { id: "v011", word: "請", pinyin: "qǐng", meaning: "please; to invite", example: "請進，坐下。", exampleEn: "Please come in and sit down.", pos: "verb", chapter: 1, tags: ["greetings"] },
  { id: "v012", word: "好", pinyin: "hǎo", meaning: "good; okay; well", example: "好的，我知道了。", exampleEn: "Okay, I understand.", pos: "adjective", chapter: 1, tags: ["greetings", "descriptions"] },
  { id: "v013", word: "是", pinyin: "shì", meaning: "to be; is; yes", example: "我是學生。", exampleEn: "I am a student.", pos: "verb", chapter: 1, tags: ["grammar"] },
  { id: "v014", word: "不", pinyin: "bù", meaning: "no; not", example: "我不喝咖啡。", exampleEn: "I don't drink coffee.", pos: "adverb", chapter: 1, tags: ["grammar"] },
  { id: "v015", word: "對", pinyin: "duì", meaning: "correct; right", example: "對，這是我的書。", exampleEn: "Correct, this is my book.", pos: "adjective", chapter: 1, tags: ["greetings"] },

  // Chapter 2 - People & Pronouns
  { id: "v016", word: "我", pinyin: "wǒ", meaning: "I; me", example: "我叫小明。", exampleEn: "My name is Xiao Ming.", pos: "pronoun", chapter: 2, tags: ["pronouns"] },
  { id: "v017", word: "你", pinyin: "nǐ", meaning: "you (singular)", example: "你是哪裡人？", exampleEn: "Where are you from?", pos: "pronoun", chapter: 2, tags: ["pronouns"] },
  { id: "v018", word: "他", pinyin: "tā", meaning: "he; him", example: "他是我的哥哥。", exampleEn: "He is my older brother.", pos: "pronoun", chapter: 2, tags: ["pronouns"] },
  { id: "v019", word: "她", pinyin: "tā", meaning: "she; her", example: "她很漂亮。", exampleEn: "She is very pretty.", pos: "pronoun", chapter: 2, tags: ["pronouns"] },
  { id: "v020", word: "我們", pinyin: "wǒ men", meaning: "we; us", example: "我們是同班同學。", exampleEn: "We are classmates.", pos: "pronoun", chapter: 2, tags: ["pronouns"] },
  { id: "v021", word: "你們", pinyin: "nǐ men", meaning: "you (plural)", example: "你們好！歡迎來到台灣。", exampleEn: "Hello everyone! Welcome to Taiwan.", pos: "pronoun", chapter: 2, tags: ["pronouns"] },
  { id: "v022", word: "他們", pinyin: "tā men", meaning: "they; them", example: "他們在圖書館學習。", exampleEn: "They are studying at the library.", pos: "pronoun", chapter: 2, tags: ["pronouns"] },
  { id: "v023", word: "人", pinyin: "rén", meaning: "person; people", example: "這裡有很多人。", exampleEn: "There are many people here.", pos: "noun", chapter: 2, tags: ["people"] },
  { id: "v024", word: "名字", pinyin: "míng zi", meaning: "name", example: "你的名字叫什麼？", exampleEn: "What is your name?", pos: "noun", chapter: 2, tags: ["people"] },
  { id: "v025", word: "朋友", pinyin: "péng yǒu", meaning: "friend", example: "她是我最好的朋友。", exampleEn: "She is my best friend.", pos: "noun", chapter: 2, tags: ["people", "social"] },
  { id: "v026", word: "同學", pinyin: "tóng xué", meaning: "classmate; fellow student", example: "我的同學很友善。", exampleEn: "My classmates are very friendly.", pos: "noun", chapter: 2, tags: ["people", "school"] },
  { id: "v027", word: "老師", pinyin: "lǎo shī", meaning: "teacher", example: "老師教我們中文。", exampleEn: "The teacher teaches us Chinese.", pos: "noun", chapter: 2, tags: ["people", "school"] },
  { id: "v028", word: "學生", pinyin: "xué shēng", meaning: "student", example: "我是大學生。", exampleEn: "I am a university student.", pos: "noun", chapter: 2, tags: ["people", "school"] },
  { id: "v029", word: "男生", pinyin: "nán shēng", meaning: "boy; male student", example: "班上有十個男生。", exampleEn: "There are ten boys in the class.", pos: "noun", chapter: 2, tags: ["people"] },
  { id: "v030", word: "女生", pinyin: "nǚ shēng", meaning: "girl; female student", example: "女生們都很可愛。", exampleEn: "All the girls are very cute.", pos: "noun", chapter: 2, tags: ["people"] },

  // Chapter 3 - Family
  { id: "v031", word: "家", pinyin: "jiā", meaning: "family; home; house", example: "我家有四個人。", exampleEn: "There are four people in my family.", pos: "noun", chapter: 3, tags: ["family"] },
  { id: "v032", word: "爸爸", pinyin: "bà ba", meaning: "dad; father", example: "爸爸每天開車上班。", exampleEn: "Dad drives to work every day.", pos: "noun", chapter: 3, tags: ["family"] },
  { id: "v033", word: "媽媽", pinyin: "mā ma", meaning: "mom; mother", example: "媽媽做的菜很好吃。", exampleEn: "The food mom cooks is delicious.", pos: "noun", chapter: 3, tags: ["family"] },
  { id: "v034", word: "哥哥", pinyin: "gē ge", meaning: "older brother", example: "我哥哥在大學讀書。", exampleEn: "My older brother studies at university.", pos: "noun", chapter: 3, tags: ["family"] },
  { id: "v035", word: "姐姐", pinyin: "jiě jie", meaning: "older sister", example: "姐姐比我高。", exampleEn: "My older sister is taller than me.", pos: "noun", chapter: 3, tags: ["family"] },
  { id: "v036", word: "弟弟", pinyin: "dì di", meaning: "younger brother", example: "弟弟很喜歡玩遊戲。", exampleEn: "My younger brother loves playing games.", pos: "noun", chapter: 3, tags: ["family"] },
  { id: "v037", word: "妹妹", pinyin: "mèi mei", meaning: "younger sister", example: "妹妹今年五歲。", exampleEn: "My younger sister is five years old this year.", pos: "noun", chapter: 3, tags: ["family"] },
  { id: "v038", word: "爺爺", pinyin: "yé ye", meaning: "paternal grandfather", example: "爺爺每天去公園散步。", exampleEn: "Grandpa goes for a walk in the park every day.", pos: "noun", chapter: 3, tags: ["family"] },
  { id: "v039", word: "奶奶", pinyin: "nǎi nai", meaning: "paternal grandmother", example: "奶奶喜歡種花。", exampleEn: "Grandma likes to grow flowers.", pos: "noun", chapter: 3, tags: ["family"] },
  { id: "v040", word: "兒子", pinyin: "ér zi", meaning: "son", example: "他的兒子很聰明。", exampleEn: "His son is very smart.", pos: "noun", chapter: 3, tags: ["family"] },
  { id: "v041", word: "女兒", pinyin: "nǚ ér", meaning: "daughter", example: "他們的女兒很可愛。", exampleEn: "Their daughter is very cute.", pos: "noun", chapter: 3, tags: ["family"] },
  { id: "v042", word: "先生", pinyin: "xiān shēng", meaning: "Mr.; husband; sir", example: "王先生，請進。", exampleEn: "Mr. Wang, please come in.", pos: "noun", chapter: 3, tags: ["family", "people"] },
  { id: "v043", word: "太太", pinyin: "tài tai", meaning: "Mrs.; wife; madam", example: "這位是我太太。", exampleEn: "This is my wife.", pos: "noun", chapter: 3, tags: ["family", "people"] },

  // Chapter 4 - Time
  { id: "v044", word: "今天", pinyin: "jīn tiān", meaning: "today", example: "今天天氣很好。", exampleEn: "The weather is nice today.", pos: "noun", chapter: 4, tags: ["time"] },
  { id: "v045", word: "昨天", pinyin: "zuó tiān", meaning: "yesterday", example: "昨天我去看電影了。", exampleEn: "I went to see a movie yesterday.", pos: "noun", chapter: 4, tags: ["time"] },
  { id: "v046", word: "明天", pinyin: "míng tiān", meaning: "tomorrow", example: "明天有考試，我要複習。", exampleEn: "There's a test tomorrow, I need to review.", pos: "noun", chapter: 4, tags: ["time"] },
  { id: "v047", word: "現在", pinyin: "xiàn zài", meaning: "now; currently", example: "現在幾點了？", exampleEn: "What time is it now?", pos: "adverb", chapter: 4, tags: ["time"] },
  { id: "v048", word: "早上", pinyin: "zǎo shàng", meaning: "morning", example: "我每天早上七點起床。", exampleEn: "I get up at seven every morning.", pos: "noun", chapter: 4, tags: ["time"] },
  { id: "v049", word: "下午", pinyin: "xià wǔ", meaning: "afternoon", example: "下午我要去圖書館。", exampleEn: "I'm going to the library this afternoon.", pos: "noun", chapter: 4, tags: ["time"] },
  { id: "v050", word: "晚上", pinyin: "wǎn shàng", meaning: "evening; night", example: "晚上我們一起吃飯吧。", exampleEn: "Let's eat together this evening.", pos: "noun", chapter: 4, tags: ["time"] },
  { id: "v051", word: "星期", pinyin: "xīng qī", meaning: "week; day of the week", example: "今天是星期幾？", exampleEn: "What day of the week is today?", pos: "noun", chapter: 4, tags: ["time"] },
  { id: "v052", word: "月", pinyin: "yuè", meaning: "month; moon", example: "一年有十二個月。", exampleEn: "There are twelve months in a year.", pos: "noun", chapter: 4, tags: ["time"] },
  { id: "v053", word: "年", pinyin: "nián", meaning: "year", example: "新年快樂！", exampleEn: "Happy New Year!", pos: "noun", chapter: 4, tags: ["time"] },
  { id: "v054", word: "點", pinyin: "diǎn", meaning: "o'clock; dot; point", example: "現在是三點半。", exampleEn: "It is now three-thirty.", pos: "noun", chapter: 4, tags: ["time"] },
  { id: "v055", word: "以前", pinyin: "yǐ qián", meaning: "before; ago; in the past", example: "以前我住在台北。", exampleEn: "I used to live in Taipei.", pos: "noun", chapter: 4, tags: ["time"] },
  { id: "v056", word: "以後", pinyin: "yǐ hòu", meaning: "after; later; in the future", example: "以後請多關照。", exampleEn: "Please take care of me in the future.", pos: "noun", chapter: 4, tags: ["time"] },

  // Chapter 5 - Places
  { id: "v057", word: "這裡", pinyin: "zhè lǐ", meaning: "here", example: "請在這裡簽名。", exampleEn: "Please sign here.", pos: "pronoun", chapter: 5, tags: ["places"] },
  { id: "v058", word: "那裡", pinyin: "nà lǐ", meaning: "there", example: "那裡有一家很好吃的餐廳。", exampleEn: "There is a very good restaurant over there.", pos: "pronoun", chapter: 5, tags: ["places"] },
  { id: "v059", word: "哪裡", pinyin: "nǎ lǐ", meaning: "where", example: "你住在哪裡？", exampleEn: "Where do you live?", pos: "pronoun", chapter: 5, tags: ["places"] },
  { id: "v060", word: "學校", pinyin: "xué xiào", meaning: "school", example: "我每天走路去學校。", exampleEn: "I walk to school every day.", pos: "noun", chapter: 5, tags: ["places", "school"] },
  { id: "v061", word: "醫院", pinyin: "yī yuàn", meaning: "hospital", example: "他生病了，去醫院看病。", exampleEn: "He got sick and went to the hospital.", pos: "noun", chapter: 5, tags: ["places", "health"] },
  { id: "v062", word: "銀行", pinyin: "yín háng", meaning: "bank", example: "我要去銀行換錢。", exampleEn: "I need to go to the bank to exchange money.", pos: "noun", chapter: 5, tags: ["places", "shopping"] },
  { id: "v063", word: "超市", pinyin: "chāo shì", meaning: "supermarket", example: "媽媽去超市買菜。", exampleEn: "Mom went to the supermarket to buy vegetables.", pos: "noun", chapter: 5, tags: ["places", "shopping"] },
  { id: "v064", word: "餐廳", pinyin: "cān tīng", meaning: "restaurant", example: "我們去那家餐廳吃飯。", exampleEn: "Let's eat at that restaurant.", pos: "noun", chapter: 5, tags: ["places", "food"] },
  { id: "v065", word: "公園", pinyin: "gōng yuán", meaning: "park", example: "週末我喜歡在公園散步。", exampleEn: "I like to take walks in the park on weekends.", pos: "noun", chapter: 5, tags: ["places"] },
  { id: "v066", word: "左邊", pinyin: "zuǒ biān", meaning: "left; left side", example: "郵局在銀行的左邊。", exampleEn: "The post office is to the left of the bank.", pos: "noun", chapter: 5, tags: ["places", "directions"] },
  { id: "v067", word: "右邊", pinyin: "yòu biān", meaning: "right; right side", example: "書店在右邊。", exampleEn: "The bookstore is on the right side.", pos: "noun", chapter: 5, tags: ["places", "directions"] },
  { id: "v068", word: "旁邊", pinyin: "páng biān", meaning: "beside; next to", example: "學校旁邊有一家便利商店。", exampleEn: "There is a convenience store next to the school.", pos: "noun", chapter: 5, tags: ["places", "directions"] },
  { id: "v069", word: "在", pinyin: "zài", meaning: "at; in; to be located at", example: "他在家嗎？", exampleEn: "Is he at home?", pos: "preposition", chapter: 5, tags: ["grammar", "places"] },

  // Chapter 6 - Food & Dining
  { id: "v070", word: "吃", pinyin: "chī", meaning: "to eat", example: "你吃飯了嗎？", exampleEn: "Have you eaten?", pos: "verb", chapter: 6, tags: ["food", "verbs"] },
  { id: "v071", word: "喝", pinyin: "hē", meaning: "to drink", example: "天氣熱，多喝水。", exampleEn: "It's hot, drink more water.", pos: "verb", chapter: 6, tags: ["food", "verbs"] },
  { id: "v072", word: "飯", pinyin: "fàn", meaning: "cooked rice; meal", example: "我早上吃稀飯。", exampleEn: "I eat congee in the morning.", pos: "noun", chapter: 6, tags: ["food"] },
  { id: "v073", word: "麵", pinyin: "miàn", meaning: "noodles", example: "我想吃牛肉麵。", exampleEn: "I want to eat beef noodles.", pos: "noun", chapter: 6, tags: ["food"] },
  { id: "v074", word: "水", pinyin: "shuǐ", meaning: "water", example: "請給我一杯水。", exampleEn: "Please give me a glass of water.", pos: "noun", chapter: 6, tags: ["food"] },
  { id: "v075", word: "茶", pinyin: "chá", meaning: "tea", example: "台灣的珍珠奶茶很有名。", exampleEn: "Taiwan's bubble milk tea is very famous.", pos: "noun", chapter: 6, tags: ["food"] },
  { id: "v076", word: "咖啡", pinyin: "kā fēi", meaning: "coffee", example: "我每天早上喝一杯咖啡。", exampleEn: "I drink a cup of coffee every morning.", pos: "noun", chapter: 6, tags: ["food"] },
  { id: "v077", word: "水果", pinyin: "shuǐ guǒ", meaning: "fruit", example: "台灣的水果又甜又多汁。", exampleEn: "Taiwan's fruit is both sweet and juicy.", pos: "noun", chapter: 6, tags: ["food"] },
  { id: "v078", word: "肉", pinyin: "ròu", meaning: "meat", example: "他不吃肉，是素食者。", exampleEn: "He doesn't eat meat, he's a vegetarian.", pos: "noun", chapter: 6, tags: ["food"] },
  { id: "v079", word: "好吃", pinyin: "hǎo chī", meaning: "delicious; tasty", example: "這個蛋糕真好吃！", exampleEn: "This cake is really delicious!", pos: "adjective", chapter: 6, tags: ["food", "descriptions"] },
  { id: "v080", word: "餓", pinyin: "è", meaning: "hungry", example: "我很餓，想吃東西。", exampleEn: "I'm very hungry and want to eat something.", pos: "adjective", chapter: 6, tags: ["food", "emotions"] },
  { id: "v081", word: "渴", pinyin: "kě", meaning: "thirsty", example: "跑步後很渴，要喝水。", exampleEn: "I'm thirsty after running, I need to drink water.", pos: "adjective", chapter: 6, tags: ["food", "emotions"] },
  { id: "v082", word: "菜", pinyin: "cài", meaning: "vegetable; dish; food", example: "這道菜是我媽媽做的。", exampleEn: "This dish was made by my mother.", pos: "noun", chapter: 6, tags: ["food"] },

  // Chapter 7 - Transportation
  { id: "v083", word: "走", pinyin: "zǒu", meaning: "to walk; to go; to leave", example: "我們走路去吧。", exampleEn: "Let's go on foot.", pos: "verb", chapter: 7, tags: ["transport", "verbs"] },
  { id: "v084", word: "坐", pinyin: "zuò", meaning: "to sit; to take (transport)", example: "我坐捷運去上班。", exampleEn: "I take the MRT to work.", pos: "verb", chapter: 7, tags: ["transport", "verbs"] },
  { id: "v085", word: "開車", pinyin: "kāi chē", meaning: "to drive (a car)", example: "爸爸每天開車送我上學。", exampleEn: "Dad drives me to school every day.", pos: "verb", chapter: 7, tags: ["transport", "verbs"] },
  { id: "v086", word: "公車", pinyin: "gōng chē", meaning: "bus", example: "我搭公車去市場。", exampleEn: "I take the bus to the market.", pos: "noun", chapter: 7, tags: ["transport"] },
  { id: "v087", word: "捷運", pinyin: "jié yùn", meaning: "MRT; metro (Taiwan)", example: "台北的捷運很方便。", exampleEn: "Taipei's MRT is very convenient.", pos: "noun", chapter: 7, tags: ["transport"] },
  { id: "v088", word: "計程車", pinyin: "jì chéng chē", meaning: "taxi", example: "叫一輛計程車去機場。", exampleEn: "Call a taxi to go to the airport.", pos: "noun", chapter: 7, tags: ["transport"] },
  { id: "v089", word: "飛機", pinyin: "fēi jī", meaning: "airplane", example: "我坐飛機去日本旅遊。", exampleEn: "I'm taking a plane to travel to Japan.", pos: "noun", chapter: 7, tags: ["transport"] },
  { id: "v090", word: "火車", pinyin: "huǒ chē", meaning: "train", example: "坐火車從台北到台南要幾個小時？", exampleEn: "How many hours does it take by train from Taipei to Tainan?", pos: "noun", chapter: 7, tags: ["transport"] },
  { id: "v091", word: "車站", pinyin: "chē zhàn", meaning: "station; bus stop", example: "我在車站等你。", exampleEn: "I'll wait for you at the station.", pos: "noun", chapter: 7, tags: ["transport", "places"] },
  { id: "v092", word: "機場", pinyin: "jī chǎng", meaning: "airport", example: "我去機場接朋友。", exampleEn: "I'm going to the airport to pick up a friend.", pos: "noun", chapter: 7, tags: ["transport", "places"] },
  { id: "v093", word: "遠", pinyin: "yuǎn", meaning: "far; distant", example: "我家離學校很遠。", exampleEn: "My home is far from school.", pos: "adjective", chapter: 7, tags: ["transport", "descriptions"] },
  { id: "v094", word: "近", pinyin: "jìn", meaning: "close; near", example: "超市離這裡很近。", exampleEn: "The supermarket is very close to here.", pos: "adjective", chapter: 7, tags: ["transport", "descriptions"] },
  { id: "v095", word: "出發", pinyin: "chū fā", meaning: "to depart; to set off", example: "我們明天早上八點出發。", exampleEn: "We depart tomorrow morning at eight.", pos: "verb", chapter: 7, tags: ["transport", "verbs"] },

  // Chapter 8 - Shopping
  { id: "v096", word: "買", pinyin: "mǎi", meaning: "to buy; to purchase", example: "我要買一件新衣服。", exampleEn: "I want to buy a new piece of clothing.", pos: "verb", chapter: 8, tags: ["shopping", "verbs"] },
  { id: "v097", word: "賣", pinyin: "mài", meaning: "to sell", example: "這裡賣很多種類的食物。", exampleEn: "Many kinds of food are sold here.", pos: "verb", chapter: 8, tags: ["shopping", "verbs"] },
  { id: "v098", word: "錢", pinyin: "qián", meaning: "money", example: "我身上沒有錢了。", exampleEn: "I have no more money on me.", pos: "noun", chapter: 8, tags: ["shopping"] },
  { id: "v099", word: "多少錢", pinyin: "duō shǎo qián", meaning: "how much (money)", example: "這件衣服多少錢？", exampleEn: "How much is this piece of clothing?", pos: "phrase", chapter: 8, tags: ["shopping"] },
  { id: "v100", word: "便宜", pinyin: "pián yi", meaning: "cheap; inexpensive", example: "這家店的東西很便宜。", exampleEn: "The things at this store are very cheap.", pos: "adjective", chapter: 8, tags: ["shopping", "descriptions"] },
  { id: "v101", word: "貴", pinyin: "guì", meaning: "expensive", example: "這個包包太貴了，我買不起。", exampleEn: "This bag is too expensive, I can't afford it.", pos: "adjective", chapter: 8, tags: ["shopping", "descriptions"] },
  { id: "v102", word: "付錢", pinyin: "fù qián", meaning: "to pay (money)", example: "請到收銀台付錢。", exampleEn: "Please pay at the checkout counter.", pos: "verb", chapter: 8, tags: ["shopping", "verbs"] },
  { id: "v103", word: "商店", pinyin: "shāng diàn", meaning: "shop; store", example: "街上有很多商店。", exampleEn: "There are many shops on the street.", pos: "noun", chapter: 8, tags: ["shopping", "places"] },
  { id: "v104", word: "衣服", pinyin: "yī fú", meaning: "clothing; clothes", example: "她有很多漂亮的衣服。", exampleEn: "She has many pretty clothes.", pos: "noun", chapter: 8, tags: ["shopping"] },
  { id: "v105", word: "鞋子", pinyin: "xié zi", meaning: "shoes", example: "我需要一雙新鞋子。", exampleEn: "I need a new pair of shoes.", pos: "noun", chapter: 8, tags: ["shopping"] },
  { id: "v106", word: "帽子", pinyin: "mào zi", meaning: "hat; cap", example: "天氣很熱，記得戴帽子。", exampleEn: "The weather is very hot, remember to wear a hat.", pos: "noun", chapter: 8, tags: ["shopping"] },
  { id: "v107", word: "打折", pinyin: "dǎ zhé", meaning: "discount; on sale", example: "這家店今天打折。", exampleEn: "This store has a discount today.", pos: "verb", chapter: 8, tags: ["shopping", "verbs"] },
  { id: "v108", word: "找錢", pinyin: "zhǎo qián", meaning: "to give change", example: "請找我五十元。", exampleEn: "Please give me fifty dollars in change.", pos: "verb", chapter: 8, tags: ["shopping", "verbs"] },

  // Chapter 9 - Colors & Descriptions
  { id: "v109", word: "紅色", pinyin: "hóng sè", meaning: "red", example: "她穿了一件紅色的裙子。", exampleEn: "She wore a red skirt.", pos: "noun", chapter: 9, tags: ["colors", "descriptions"] },
  { id: "v110", word: "藍色", pinyin: "lán sè", meaning: "blue", example: "今天的天空是藍色的。", exampleEn: "Today's sky is blue.", pos: "noun", chapter: 9, tags: ["colors", "descriptions"] },
  { id: "v111", word: "綠色", pinyin: "lǜ sè", meaning: "green", example: "春天的草地是綠色的。", exampleEn: "The meadows are green in spring.", pos: "noun", chapter: 9, tags: ["colors", "descriptions"] },
  { id: "v112", word: "白色", pinyin: "bái sè", meaning: "white", example: "他喜歡穿白色的衣服。", exampleEn: "He likes to wear white clothes.", pos: "noun", chapter: 9, tags: ["colors", "descriptions"] },
  { id: "v113", word: "黑色", pinyin: "hēi sè", meaning: "black", example: "黑色的包包很好搭衣服。", exampleEn: "Black bags match clothes easily.", pos: "noun", chapter: 9, tags: ["colors", "descriptions"] },
  { id: "v114", word: "黃色", pinyin: "huáng sè", meaning: "yellow", example: "香蕉是黃色的。", exampleEn: "Bananas are yellow.", pos: "noun", chapter: 9, tags: ["colors", "descriptions"] },
  { id: "v115", word: "大", pinyin: "dà", meaning: "big; large", example: "台北是一個很大的城市。", exampleEn: "Taipei is a very large city.", pos: "adjective", chapter: 9, tags: ["descriptions"] },
  { id: "v116", word: "小", pinyin: "xiǎo", meaning: "small; little", example: "我的房間很小。", exampleEn: "My room is very small.", pos: "adjective", chapter: 9, tags: ["descriptions"] },
  { id: "v117", word: "高", pinyin: "gāo", meaning: "tall; high", example: "台北101是很高的大樓。", exampleEn: "Taipei 101 is a very tall building.", pos: "adjective", chapter: 9, tags: ["descriptions"] },
  { id: "v118", word: "矮", pinyin: "ǎi", meaning: "short (height)", example: "他比我矮一點。", exampleEn: "He is a little shorter than me.", pos: "adjective", chapter: 9, tags: ["descriptions"] },
  { id: "v119", word: "漂亮", pinyin: "piào liàng", meaning: "beautiful; pretty", example: "這朵花真漂亮！", exampleEn: "This flower is so beautiful!", pos: "adjective", chapter: 9, tags: ["descriptions"] },
  { id: "v120", word: "可愛", pinyin: "kě ài", meaning: "cute; adorable", example: "那隻小狗好可愛！", exampleEn: "That puppy is so cute!", pos: "adjective", chapter: 9, tags: ["descriptions"] },
  { id: "v121", word: "帥", pinyin: "shuài", meaning: "handsome; cool", example: "那個演員很帥。", exampleEn: "That actor is very handsome.", pos: "adjective", chapter: 9, tags: ["descriptions"] },

  // Chapter 10 - Common Verbs & Actions
  { id: "v122", word: "說", pinyin: "shuō", meaning: "to say; to speak; to talk", example: "她會說三種語言。", exampleEn: "She can speak three languages.", pos: "verb", chapter: 10, tags: ["verbs", "communication"] },
  { id: "v123", word: "聽", pinyin: "tīng", meaning: "to listen; to hear", example: "我喜歡聽音樂。", exampleEn: "I like to listen to music.", pos: "verb", chapter: 10, tags: ["verbs"] },
  { id: "v124", word: "看", pinyin: "kàn", meaning: "to look; to see; to watch; to read", example: "我昨晚看了一部好電影。", exampleEn: "I watched a good movie last night.", pos: "verb", chapter: 10, tags: ["verbs"] },
  { id: "v125", word: "寫", pinyin: "xiě", meaning: "to write", example: "請在這裡寫下你的名字。", exampleEn: "Please write your name here.", pos: "verb", chapter: 10, tags: ["verbs", "school"] },
  { id: "v126", word: "學", pinyin: "xué", meaning: "to learn; to study", example: "我學中文學了兩年。", exampleEn: "I have been learning Chinese for two years.", pos: "verb", chapter: 10, tags: ["verbs", "school"] },
  { id: "v127", word: "做", pinyin: "zuò", meaning: "to do; to make", example: "你在做什麼？", exampleEn: "What are you doing?", pos: "verb", chapter: 10, tags: ["verbs"] },
  { id: "v128", word: "去", pinyin: "qù", meaning: "to go", example: "我們一起去爬山吧！", exampleEn: "Let's go hiking together!", pos: "verb", chapter: 10, tags: ["verbs", "transport"] },
  { id: "v129", word: "來", pinyin: "lái", meaning: "to come", example: "歡迎來台灣！", exampleEn: "Welcome to Taiwan!", pos: "verb", chapter: 10, tags: ["verbs", "transport"] },
  { id: "v130", word: "玩", pinyin: "wán", meaning: "to play; to have fun", example: "小孩子們在公園玩。", exampleEn: "The children are playing in the park.", pos: "verb", chapter: 10, tags: ["verbs"] },
  { id: "v131", word: "睡覺", pinyin: "shuì jiào", meaning: "to sleep", example: "我每天晚上十一點睡覺。", exampleEn: "I go to sleep at eleven every night.", pos: "verb", chapter: 10, tags: ["verbs", "daily life"] },
  { id: "v132", word: "上班", pinyin: "shàng bān", meaning: "to go to work; to be at work", example: "爸爸每天早上八點上班。", exampleEn: "Dad goes to work at eight every morning.", pos: "verb", chapter: 10, tags: ["verbs", "work"] },
  { id: "v133", word: "下班", pinyin: "xià bān", meaning: "to get off work; to finish work", example: "他五點下班，然後去健身房。", exampleEn: "He gets off work at five, then goes to the gym.", pos: "verb", chapter: 10, tags: ["verbs", "work"] },
  { id: "v134", word: "考試", pinyin: "kǎo shì", meaning: "exam; test; to take an exam", example: "明天有中文考試。", exampleEn: "There is a Chinese exam tomorrow.", pos: "noun", chapter: 10, tags: ["school"] },
];

const CHARACTERS = [
  // Chapter 1 - Simple & Basic
  { id: "c001", character: "一", pinyin: "yī", meaning: "one", strokes: 1, examples: ["一個", "第一", "一起"], examplesEn: ["one (counter)", "first", "together"], chapter: 1 },
  { id: "c002", character: "二", pinyin: "èr", meaning: "two", strokes: 2, examples: ["二月", "第二", "十二"], examplesEn: ["February", "second", "twelve"], chapter: 1 },
  { id: "c003", character: "三", pinyin: "sān", meaning: "three", strokes: 3, examples: ["三月", "第三", "三角形"], examplesEn: ["March", "third", "triangle"], chapter: 1 },
  { id: "c004", character: "人", pinyin: "rén", meaning: "person; people", strokes: 2, examples: ["人口", "外國人", "個人"], examplesEn: ["population", "foreigner", "individual"], chapter: 1 },
  { id: "c005", character: "口", pinyin: "kǒu", meaning: "mouth; opening", strokes: 3, examples: ["人口", "開口", "入口"], examplesEn: ["population", "to open one's mouth", "entrance"], chapter: 1 },
  { id: "c006", character: "日", pinyin: "rì", meaning: "sun; day; Japan", strokes: 4, examples: ["日本", "生日", "日記"], examplesEn: ["Japan", "birthday", "diary"], chapter: 1 },
  { id: "c007", character: "月", pinyin: "yuè", meaning: "moon; month", strokes: 4, examples: ["月亮", "每月", "月份"], examplesEn: ["moon", "every month", "month"], chapter: 1 },
  { id: "c008", character: "山", pinyin: "shān", meaning: "mountain", strokes: 3, examples: ["山頂", "火山", "爬山"], examplesEn: ["mountain top", "volcano", "mountain climbing"], chapter: 1 },
  { id: "c009", character: "水", pinyin: "shuǐ", meaning: "water", strokes: 4, examples: ["水果", "喝水", "水平"], examplesEn: ["fruit", "to drink water", "horizontal/level"], chapter: 1 },
  { id: "c010", character: "火", pinyin: "huǒ", meaning: "fire", strokes: 4, examples: ["火車", "火山", "火鍋"], examplesEn: ["train", "volcano", "hot pot"], chapter: 1 },

  // Chapter 2 - Directions & Basics
  { id: "c011", character: "大", pinyin: "dà", meaning: "big; large", strokes: 3, examples: ["大學", "大家", "大小"], examplesEn: ["university", "everyone", "size"], chapter: 2 },
  { id: "c012", character: "小", pinyin: "xiǎo", meaning: "small; little", strokes: 3, examples: ["小學", "小姐", "大小"], examplesEn: ["elementary school", "miss", "size"], chapter: 2 },
  { id: "c013", character: "中", pinyin: "zhōng", meaning: "middle; center; China", strokes: 4, examples: ["中文", "中間", "中國"], examplesEn: ["Chinese language", "middle/between", "China"], chapter: 2 },
  { id: "c014", character: "上", pinyin: "shàng", meaning: "up; above; on; to go to", strokes: 3, examples: ["上課", "以上", "上班"], examplesEn: ["to attend class", "above/more than", "to go to work"], chapter: 2 },
  { id: "c015", character: "下", pinyin: "xià", meaning: "down; below; under", strokes: 3, examples: ["下課", "以下", "下午"], examplesEn: ["after class", "below/less than", "afternoon"], chapter: 2 },
  { id: "c016", character: "女", pinyin: "nǚ", meaning: "woman; female", strokes: 3, examples: ["女生", "女兒", "女性"], examplesEn: ["girl", "daughter", "female"], chapter: 2 },
  { id: "c017", character: "子", pinyin: "zǐ", meaning: "child; son; small thing", strokes: 3, examples: ["孩子", "兒子", "子女"], examplesEn: ["child", "son", "children"], chapter: 2 },
  { id: "c018", character: "天", pinyin: "tiān", meaning: "sky; heaven; day; weather", strokes: 4, examples: ["天氣", "今天", "天空"], examplesEn: ["weather", "today", "sky"], chapter: 2 },
  { id: "c019", character: "白", pinyin: "bái", meaning: "white; clear; blank", strokes: 5, examples: ["白色", "明白", "空白"], examplesEn: ["white", "to understand", "blank"], chapter: 2 },
  { id: "c020", character: "木", pinyin: "mù", meaning: "wood; tree", strokes: 4, examples: ["木頭", "木材", "積木"], examplesEn: ["wood/timber", "lumber", "building blocks"], chapter: 2 },

  // Chapter 3 - Numbers & Time
  { id: "c021", character: "百", pinyin: "bǎi", meaning: "hundred", strokes: 6, examples: ["一百", "百元", "百分之"], examplesEn: ["one hundred", "hundred dollars", "percent"], chapter: 3 },
  { id: "c022", character: "千", pinyin: "qiān", meaning: "thousand", strokes: 3, examples: ["一千", "幾千", "千萬"], examplesEn: ["one thousand", "several thousand", "absolutely/ten million"], chapter: 3 },
  { id: "c023", character: "萬", pinyin: "wàn", meaning: "ten thousand; myriad", strokes: 13, examples: ["一萬", "百萬", "萬歲"], examplesEn: ["ten thousand", "one million", "long live"], chapter: 3 },
  { id: "c024", character: "年", pinyin: "nián", meaning: "year", strokes: 6, examples: ["今年", "新年", "去年"], examplesEn: ["this year", "New Year", "last year"], chapter: 3 },
  { id: "c025", character: "時", pinyin: "shí", meaning: "time; hour; o'clock", strokes: 10, examples: ["時間", "小時", "有時"], examplesEn: ["time", "hour", "sometimes"], chapter: 3 },
  { id: "c026", character: "分", pinyin: "fēn", meaning: "minute; part; to divide", strokes: 4, examples: ["分鐘", "十分", "部分"], examplesEn: ["minute", "very/fully", "part/portion"], chapter: 3 },
  { id: "c027", character: "今", pinyin: "jīn", meaning: "today; present; now", strokes: 4, examples: ["今天", "今年", "今後"], examplesEn: ["today", "this year", "from now on"], chapter: 3 },
  { id: "c028", character: "明", pinyin: "míng", meaning: "bright; clear; tomorrow", strokes: 8, examples: ["明天", "明白", "聰明"], examplesEn: ["tomorrow", "to understand", "smart/clever"], chapter: 3 },
  { id: "c029", character: "先", pinyin: "xiān", meaning: "first; before; earlier", strokes: 6, examples: ["先生", "首先", "先後"], examplesEn: ["Mr./husband", "first of all", "order/sequence"], chapter: 3 },
  { id: "c030", character: "後", pinyin: "hòu", meaning: "after; behind; back", strokes: 9, examples: ["以後", "後來", "後面"], examplesEn: ["after/later", "afterwards", "behind"], chapter: 3 },

  // Chapter 4 - People & Relationships
  { id: "c031", character: "我", pinyin: "wǒ", meaning: "I; me; my", strokes: 7, examples: ["我們", "自我", "我的"], examplesEn: ["we/us", "self", "my/mine"], chapter: 4 },
  { id: "c032", character: "你", pinyin: "nǐ", meaning: "you (informal)", strokes: 7, examples: ["你好", "你們", "你的"], examplesEn: ["hello", "you (plural)", "your/yours"], chapter: 4 },
  { id: "c033", character: "他", pinyin: "tā", meaning: "he; him; his", strokes: 5, examples: ["他們", "其他", "他的"], examplesEn: ["they/them", "other/others", "his"], chapter: 4 },
  { id: "c034", character: "父", pinyin: "fù", meaning: "father", strokes: 4, examples: ["父親", "父母", "神父"], examplesEn: ["father", "parents", "priest/father"], chapter: 4 },
  { id: "c035", character: "母", pinyin: "mǔ", meaning: "mother", strokes: 5, examples: ["母親", "父母", "母語"], examplesEn: ["mother", "parents", "mother tongue"], chapter: 4 },
  { id: "c036", character: "兄", pinyin: "xiōng", meaning: "older brother", strokes: 5, examples: ["兄弟", "兄長", "表兄"], examplesEn: ["brothers", "older brother", "male cousin"], chapter: 4 },
  { id: "c037", character: "弟", pinyin: "dì", meaning: "younger brother", strokes: 7, examples: ["弟弟", "兄弟", "子弟"], examplesEn: ["younger brother", "brothers", "young person"], chapter: 4 },
  { id: "c038", character: "友", pinyin: "yǒu", meaning: "friend; friendly", strokes: 4, examples: ["朋友", "友好", "友情"], examplesEn: ["friend", "friendly/amicable", "friendship"], chapter: 4 },
  { id: "c039", character: "男", pinyin: "nán", meaning: "male; man; boy", strokes: 7, examples: ["男生", "男人", "男女"], examplesEn: ["boy/male", "man", "men and women"], chapter: 4 },
  { id: "c040", character: "心", pinyin: "xīn", meaning: "heart; mind; feeling", strokes: 4, examples: ["心情", "中心", "開心"], examplesEn: ["mood/feeling", "center", "happy"], chapter: 4 },

  // Chapter 5 - Nature & Objects
  { id: "c041", character: "手", pinyin: "shǒu", meaning: "hand", strokes: 4, examples: ["手機", "手錶", "握手"], examplesEn: ["mobile phone", "wristwatch", "handshake"], chapter: 5 },
  { id: "c042", character: "目", pinyin: "mù", meaning: "eye; item; section", strokes: 5, examples: ["注目", "目的", "科目"], examplesEn: ["to pay attention", "purpose/goal", "subject/course"], chapter: 5 },
  { id: "c043", character: "耳", pinyin: "ěr", meaning: "ear", strokes: 6, examples: ["耳朵", "耳機", "耳環"], examplesEn: ["ear", "earphones", "earrings"], chapter: 5 },
  { id: "c044", character: "門", pinyin: "mén", meaning: "door; gate; family", strokes: 8, examples: ["門口", "開門", "專門"], examplesEn: ["doorway/entrance", "to open a door", "specialized/expert"], chapter: 5 },
  { id: "c045", character: "車", pinyin: "chē", meaning: "vehicle; car", strokes: 7, examples: ["汽車", "車站", "開車"], examplesEn: ["car/automobile", "station/stop", "to drive"], chapter: 5 },
  { id: "c046", character: "書", pinyin: "shū", meaning: "book; to write", strokes: 10, examples: ["書包", "讀書", "圖書館"], examplesEn: ["schoolbag", "to read/study", "library"], chapter: 5 },
  { id: "c047", character: "魚", pinyin: "yú", meaning: "fish", strokes: 11, examples: ["魚肉", "金魚", "釣魚"], examplesEn: ["fish meat", "goldfish", "to fish/fishing"], chapter: 5 },
  { id: "c048", character: "花", pinyin: "huā", meaning: "flower; to spend", strokes: 8, examples: ["花園", "開花", "花費"], examplesEn: ["flower garden", "to bloom", "to spend/cost"], chapter: 5 },
  { id: "c049", character: "草", pinyin: "cǎo", meaning: "grass; herb; draft", strokes: 10, examples: ["草地", "草原", "藥草"], examplesEn: ["lawn/grassland", "grassland/prairie", "herb/medicinal plant"], chapter: 5 },
  { id: "c050", character: "雨", pinyin: "yǔ", meaning: "rain", strokes: 8, examples: ["下雨", "雨天", "暴雨"], examplesEn: ["to rain", "rainy day", "rainstorm"], chapter: 5 },

  // Chapter 6 - Common Action Characters
  { id: "c051", character: "來", pinyin: "lái", meaning: "to come; to arrive", strokes: 8, examples: ["來到", "未來", "來自"], examplesEn: ["to arrive", "future", "to come from"], chapter: 6 },
  { id: "c052", character: "去", pinyin: "qù", meaning: "to go; to leave", strokes: 5, examples: ["去年", "過去", "去世"], examplesEn: ["last year", "past", "to pass away"], chapter: 6 },
  { id: "c053", character: "吃", pinyin: "chī", meaning: "to eat", strokes: 6, examples: ["吃飯", "好吃", "吃虧"], examplesEn: ["to eat a meal", "delicious", "to suffer a loss"], chapter: 6 },
  { id: "c054", character: "喝", pinyin: "hē", meaning: "to drink", strokes: 12, examples: ["喝水", "喝茶", "喝酒"], examplesEn: ["to drink water", "to drink tea", "to drink alcohol"], chapter: 6 },
  { id: "c055", character: "看", pinyin: "kàn", meaning: "to look; to watch; to read", strokes: 9, examples: ["看書", "看病", "好看"], examplesEn: ["to read", "to see a doctor", "attractive/good-looking"], chapter: 6 },
  { id: "c056", character: "說", pinyin: "shuō", meaning: "to speak; to say; to tell", strokes: 14, examples: ["說話", "說明", "小說"], examplesEn: ["to talk/speak", "to explain", "novel"], chapter: 6 },
  { id: "c057", character: "學", pinyin: "xué", meaning: "to learn; to study; school", strokes: 16, examples: ["學生", "學習", "大學"], examplesEn: ["student", "to study/learn", "university"], chapter: 6 },
  { id: "c058", character: "愛", pinyin: "ài", meaning: "love; to love; to like", strokes: 13, examples: ["愛情", "可愛", "愛護"], examplesEn: ["romantic love", "cute/adorable", "to cherish/protect"], chapter: 6 },
  { id: "c059", character: "好", pinyin: "hǎo", meaning: "good; well; very", strokes: 6, examples: ["好吃", "好看", "友好"], examplesEn: ["delicious", "attractive", "friendly/amicable"], chapter: 6 },
  { id: "c060", character: "多", pinyin: "duō", meaning: "many; much; more", strokes: 6, examples: ["多少", "很多", "多謝"], examplesEn: ["how many/how much", "a lot", "many thanks"], chapter: 6 },
];

const GRAMMAR = [
  { id: "g001", pattern: "是...的", meaning: "emphatic construction for past events", usage: "Emphasizes the time, place, manner, or agent of a completed action. The sentence describes something that already happened.", example: "我是昨天來的。", exampleEn: "I came yesterday (emphasis on when).", category: "particles", level: "intermediate" },
  { id: "g002", pattern: "把 (bǎ)", meaning: "disposal construction — moves object before verb", usage: "Used to indicate that the subject disposes of or does something to the object. The object must be definite/known.", example: "請把這本書還給我。", exampleEn: "Please return this book to me.", category: "particles", level: "intermediate" },
  { id: "g003", pattern: "被 (bèi)", meaning: "passive voice marker", usage: "Indicates that the subject receives the action (passive). Often used when the result is undesirable or unexpected.", example: "我的錢包被偷了。", exampleEn: "My wallet was stolen.", category: "particles", level: "intermediate" },
  { id: "g004", pattern: "因為...所以", meaning: "because...therefore", usage: "Expresses a cause-and-effect relationship. Both clauses can stand alone, but together emphasize the relationship.", example: "因為下雨，所以我沒出門。", exampleEn: "Because it rained, I didn't go out.", category: "conjunctions", level: "elementary" },
  { id: "g005", pattern: "雖然...但是", meaning: "although...but", usage: "Expresses a concession — something is true, but another thing is also true and seems contradictory.", example: "雖然很貴，但是我還是買了。", exampleEn: "Although it was expensive, I still bought it.", category: "conjunctions", level: "intermediate" },
  { id: "g006", pattern: "如果...就", meaning: "if...then", usage: "Expresses a conditional relationship. 如果 introduces the condition, 就 introduces the result.", example: "如果明天下雨，我就不去了。", exampleEn: "If it rains tomorrow, I won't go.", category: "conjunctions", level: "intermediate" },
  { id: "g007", pattern: "不但...而且", meaning: "not only...but also", usage: "Adds additional information that goes beyond the first point, often escalating in degree.", example: "她不但聰明，而且很努力。", exampleEn: "She is not only smart, but also very hard-working.", category: "conjunctions", level: "intermediate" },
  { id: "g008", pattern: "越來越...", meaning: "more and more; increasingly", usage: "Indicates a gradual increase in degree or quantity over time.", example: "天氣越來越熱了。", exampleEn: "The weather is getting hotter and hotter.", category: "adverbs", level: "elementary" },
  { id: "g009", pattern: "有點 (yǒu diǎn)", meaning: "a little bit; somewhat (slightly negative)", usage: "Indicates a small degree. Often used for things that are slightly undesirable or inconvenient.", example: "這道菜有點鹹。", exampleEn: "This dish is a little salty.", category: "adverbs", level: "elementary" },
  { id: "g010", pattern: "比 (bǐ)", meaning: "comparison — more than; -er than", usage: "Used to make direct comparisons between two things. The structure is: A 比 B + adjective.", example: "他比我高。", exampleEn: "He is taller than me.", category: "comparison", level: "elementary" },
  { id: "g011", pattern: "了 (le)", meaning: "completed action or changed state", usage: "Attached to verbs to show completion, or at the end of sentences to show a change in situation. Context determines meaning.", example: "我吃飯了。", exampleEn: "I've eaten. / I ate.", category: "particles", level: "elementary" },
  { id: "g012", pattern: "過 (guò)", meaning: "past experience marker", usage: "Indicates that an action has been experienced at some unspecified time in the past. Like 'have ever done'.", example: "我去過台灣。", exampleEn: "I have been to Taiwan (before).", category: "particles", level: "elementary" },
  { id: "g013", pattern: "著 (zhe)", meaning: "continuous state; doing while...", usage: "Indicates an ongoing state or action. Also used to describe doing one action simultaneously with another.", example: "她笑著對我說話。", exampleEn: "She spoke to me while smiling.", category: "particles", level: "intermediate" },
  { id: "g014", pattern: "再 (zài)", meaning: "do again (future action)", usage: "Used for actions that will happen again in the future. Compare with 又 (yòu) which refers to repetition in the past.", example: "請再說一次。", exampleEn: "Please say it once more.", category: "adverbs", level: "elementary" },
  { id: "g015", pattern: "又 (yòu)", meaning: "did again (past); both...and", usage: "Refers to an action that was repeated in the past. Also used to show two simultaneous qualities.", example: "他又來了。", exampleEn: "He came again.", category: "adverbs", level: "elementary" },
  { id: "g016", pattern: "才 (cái)", meaning: "only then; just barely; not until", usage: "Indicates that something happened later than expected, or that a condition must be met first.", example: "學了一年，我才能說一點中文。", exampleEn: "After studying for a year, I could only speak a little Chinese.", category: "adverbs", level: "intermediate" },
  { id: "g017", pattern: "就 (jiù)", meaning: "then; right away; already; as soon as", usage: "Has many uses: indicating immediacy, fulfillment of a condition, or something happening sooner than expected.", example: "我一到家就睡了。", exampleEn: "As soon as I got home, I fell asleep.", category: "adverbs", level: "elementary" },
  { id: "g018", pattern: "一邊...一邊", meaning: "doing...while simultaneously doing", usage: "Describes two actions happening at the same time by the same subject.", example: "他一邊吃飯一邊看電視。", exampleEn: "He eats while watching TV.", category: "adverbs", level: "intermediate" },
  { id: "g019", pattern: "除了...以外", meaning: "except for; besides; in addition to", usage: "Can be exclusive (except for) or inclusive (in addition to). Context and rest of sentence determine meaning.", example: "除了他以外，大家都來了。", exampleEn: "Everyone came except for him.", category: "conjunctions", level: "intermediate" },
  { id: "g020", pattern: "越...越...", meaning: "the more...the more", usage: "Shows that as one thing increases, another thing increases proportionally.", example: "你越說，我越不懂。", exampleEn: "The more you say, the less I understand.", category: "adverbs", level: "intermediate" },
];
